name: Uuenda uudiseid

on:
  schedule:
    - cron: '0 8 * * *' # Käivitub iga päev kell 8:00 UTC
  workflow_dispatch: # Lubab sul ka käsitsi nupust käivitada

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kood
        uses: actions/checkout@v2

      - name: Seadista Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installi asjad
        run: pip install -r requirements.txt

      - name: Käivita skript
        run: python scraper.py

      - name: Salvesta muudatused
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add uudised.json
          git commit -m "Uuendatud uudised" || exit 0
          git push
